(setq user-init-file "C:/Users/Henry/.emacs.d/.emacs")
(setq user-emacs-directory "C:/path/to/.emacs.d/")
(setq default-directory "C:/Users/Henry/")
(setenv "HOME" "C:/Users/Henry/")
(load user-init-file)
